### ISSUE TITLE
Initialization failed with error TrackingInitError

### ISSUE THREAD

**Issue by saravanan72** [hypertrack/quickstart-android#10]
When I go with the app initialization it responds like the below in android studio.

GetAuthDataStep: Auth token step failed with error com.android.volley.NoConnectionError: java.net.UnknownHostException: Unable to resolve host "live-api.htprod.hypertrack.com": No address associated with hostname

Please give me solution asap. thanks.

**Comment by ykravch** [comment]
@saravanan72 it might be related to your Internet connection configuration. Please make sure your DNS server is working correctly.  Simple command-line request `dig live-api.htprod.hypertrack.com`  will show if there is a problem.
