### ISSUE TITLE
Could not resolve com.hypertrack:hypertrack:3.5.0

### ISSUE THREAD

**Issue by RazibKani** [hypertrack/quickstart-android#11]
Hi, 

Need advice, I got this error when building on jenkins

```
* What went wrong:
Could not resolve all files for configuration ':app:stagingDebugCompileClasspath'.
> Could not resolve com.hypertrack:hypertrack:3.5.0.
  Required by:
      project :app
   > Could not resolve com.hypertrack:hypertrack:3.5.0.
      > Could not get resource 'http://m2.hypertrack.com/com/hypertrack/hypertrack/3.5.0/hypertrack-3.5.0.pom'.
         > Could not GET 'http://m2.hypertrack.com/com/hypertrack/hypertrack/3.5.0/hypertrack-3.5.0.pom'.
            > m2.hypertrack.com
```

Thank you

**Comment by deniszpua** [comment]
Hey @RazibKani!
Is it reproducible?
Our repo is hosted on AWS S3 and they had some issues right now.
But I'm able to fetch the artifact:
```
$ wget "http://m2.hypertrack.com/com/hypertrack/hypertrack/3.5.0/hypertrack-3.5.0.pom"
--2019-10-23 13:41:59--  http://m2.hypertrack.com/com/hypertrack/hypertrack/3.5.0/hypertrack-3.5.0.pom
Resolving m2.hypertrack.com (m2.hypertrack.com)... 52.218.225.34
Connecting to m2.hypertrack.com (m2.hypertrack.com)|52.218.225.34|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1929 (1.9K) [binary/octet-stream]
Saving to: ‘hypertrack-3.5.0.pom’

hypertrack-3.5.0.po 100%[===================>]   1.88K  --.-KB/s    in 0.001s  

2019-10-23 13:42:00 (1.26 MB/s) - ‘hypertrack-3.5.0.pom’ saved [1929/1929]


```

**Comment by RazibKani** [comment]
Hi Deniz,

It's still happens on version 3.5.0
but it work with version 3.4.3

**Comment by deniszpua** [comment]
Probably _3.4.3_ is inside gradle/maven cache.
If you wish, you can [download library](https://s3-us-west-2.amazonaws.com/m2.hypertrack.com/com/hypertrack/hypertrack/3.5.0/hypertrack-3.5.0.aar) place it inside `libs` folder of your project and try to rebuild.
Anyway, I would suggest to wait/retry, since yesterday I had exactly the same issues with AWS S3 service and now it works just fine.

**Comment by deniszpua** [comment]
Hey, I observed connectivity issues with AWS S3 yesterday and today it works just fine.
Anyway, if you didn't feel like waiting, you can [download library copy](https://s3-us-west-2.amazonaws.com/m2.hypertrack.com/com/hypertrack/hypertrack/3.5.0/hypertrack-3.5.0.aar) into `libs` dir of your project and build it with local dependency.

**Comment by RazibKani** [comment]
Hi Deniz,

for now I locally place it inside libs folder, I need to quickfix startForegroundService() on Android Pie.

Thank you for your support
