### ISSUE TITLE
setDeviceMetadata is not worrking

### ISSUE THREAD

**Issue by panchalAlpit** [hypertrack/quickstart-android#19]
I'm using SDK but it's not working, I set the device name, metadata, addTripMarker all are not working. 
Three days to try this but it's not working.

**Comment by deniszpua** [comment]
Hey @panchalAlpit, what kind of error do you get?
Feel free to ping me on [Slack](https://join.slack.com/t/hypertracksupport/shared_invite/enQtNDA0MDYxMzY1MDMxLTdmNDQ1ZDA1MTQxOTU2NTgwZTNiMzUyZDk0OThlMmJkNmE0ZGI2NGY2ZGRhYjY0Yzc0NTJlZWY2ZmE5ZTA2NjI) for faster response.
