### ISSUE TITLE
Get speed 

### ISSUE THREAD

**Issue by SheikhZayed** [hypertrack/quickstart-android#22]
Is it possible to get the speed of the device in km/h

**Comment by tulushev** [comment]
Hey @SheikhZayed we expose speed data in webhooks location stream https://hypertrack.com/docs/guides/stream-locations-and-markers-via-webhooks#location-updates 
You can also use our native Views SDKs to get this stream on mobile devices: https://hypertrack.com/docs/guides/stream-data-to-native-apps/#live-location-streaming-on-android

We have a Slack support channel where you are welcome to ask any product related questions, here is an invite: https://join.slack.com/t/hypertracksupport/shared_invite/enQtNDA0MDYxMzY1MDMxLTdmNDQ1ZDA1MTQxOTU2NTgwZTNiMzUyZDk0OThlMmJkNmE0ZGI2NGY2ZGRhYjY0Yzc0NTJlZWY2ZmE5ZTA2NjI

I'll close the issue to keep all issues more bug focused.
