### ISSUE TITLE
Hypertrack SDK is not running

### ISSUE THREAD

**Issue by jaballogian** [hypertrack/quickstart-android#24]
Hello,

I tried to follow this https://github.com/hypertrack/quickstart-android#readme readme file
But when I ran the app, the HyperTrack SDK was not running

## Computer version:
* OS version: Windows 10 Home 64-bit build 19042
* Android Studio version: 4.1.1
* Gradle version: 3.6.4 (as same as the Gradle used in this repository)

## Device (smartphone) version:
* OS version: Android 10
* Device manufacturer: Realme
* Device model: Realme 6 (RMX2001)

## Expected Behavior
The HyperTrack SDK is running when the app is running as seen in this picture https://github.com/hypertrack/quickstart-android/raw/master/Images/On_Device.png.

## Actual Behavior
The HyperTrack SDK is running when the app is running.
The proof: the background color of the label TextView is still black (not green) as seen in the picture below
<details>
<summary>
Picture
</summary>

![phon2](https://user-images.githubusercontent.com/24468466/117412184-ad952d00-af3e-11eb-82e0-d8ec84cfc7d8.png)
</details>

## Steps to Reproduce
I literally did the same as the steps in this https://github.com/hypertrack/quickstart-android#readme readme file
1. Clone this repository
2. Open the ```quickstart-java``` application using Android Studio
3. Log in to HyperTrack account
4. Go to the setup page in the HyperTrack dashboard
5. Copy the publishable key from the setup page in the dashboard
6. Open the ```MainActivity.java``` file
7. Paste the publishable key to ```MainActivity.java``` file
8. Go to Firebase console
9. Create a new Firebase project
10. Register this app using ```com.hypertrack.quickstart.android.github``` package name to the Firebase project
11. Download the ```google-services.json file``` from the Firebase project
12. Copy the ```google-services.json file``` file and paste it inside the ```/quickstart-java/app``` folder
13. Go to project setting in Firebase project
14. Go to ```Cloud Messaging``` tab in Firebase project setting page
15. Copy the token from the server key section
16. Go to setup page in the Hypertrack dashboard
17. Paste the token inside ```Server to Device communication``` (FCM) section
18. Run this app
19. Allow all permissions

## Debug

The background color of the label TextView is black because ```onTrackingStop``` function inside MainActivity.java is called.
```java
@Override
public void onTrackingStop() {
    trackingStatusLabel.setBackgroundColor(getResources().getColor(R.color.colorLabelStopped));
    trackingStatusLabel.setText(R.string.tracking_stopped);

}
```
The ```onTrackingStop``` function is called because the SDK is not running inside ```onResume``` function
```java
@Override
protected void onResume() {
    super.onResume();
    Log.d(TAG, "onResume");
    if (sdkInstance.isRunning()) {
        onTrackingStart();
    } else {
        onTrackingStop();
    }

    sdkInstance.requestPermissionsIfNecessary();
}
```

## Other Information
* I have turned on the location service but the SDK is still not running
* I have checked the Home and Playground sections from the HyperTrack dashboard and my phone was available there but the I couldn't track it as seen in the picture below
<details>
<summary>
Picture
</summary>

![Capture 4](https://user-images.githubusercontent.com/24468466/117279405-e2947780-ae8b-11eb-8788-967a1f5588e3.PNG)
</details>

## Other Questions
* I wonder why doesn't the AndroidManifest.xml file request the location permission as seen in this documentation?

**Comment by deniszpua** [comment]
Hey @jaballogian!
Thanks for trying out HyperTrack )
In order to start tracking from Playground, you need to select your device first, and then press _Start Traking_ button that appears after selection is done. Alternatively, you can create a trip for the device, but anyway you need to select it in left column first.
As for the permissions, they are declared at HyperTrack SDK level. You can see them if choose *Merged Manifest* option in Android Studio (it appears at the bottom of text window, when you look at any `AndroidManifest.xml` file).
Looking forward to seeing your product with our SDK!

**Comment by jaballogian** [comment]
Thanks for your answer

There are 2 devices in the left column panel (one of them is mine).
There are a lot of option differences in the Playground for my device and the other as seen in this picture.
<details>
<summary>
Picture
</summary>

![Capture 5](https://user-images.githubusercontent.com/24468466/117387984-0b604f80-af14-11eb-9a14-4810e1ac7f5d.PNG)
</details>

There is no "start tracking" button, no "new trip" button, and no marker of the device location on the map like the other device.

**Comment by jaballogian** [comment]
I just open a same issue in other HyperTrack app https://github.com/hypertrack/live-app-android/issues/36

So I assume that the problem is with my smartphone but I don't know what 😂😂😂

**Comment by jaballogian** [comment]
I tried using another smartphone with this specification:
* OS version: Android 10
* Device manufacturer: Realme
* Device model: Realme 7i (RMX2103)

I got the same result (HyperTrack SDK was not running) as seen in the screenshots below
<details>
<summary>
Pictures
</summary>

![Screenshot_2021-05-07-14-16-30-51](https://user-images.githubusercontent.com/24468466/117413037-b1757f00-af3f-11eb-9d3b-eb1248e33f94.jpg)

![Capture 6](https://user-images.githubusercontent.com/24468466/117413290-fdc0bf00-af3f-11eb-9bfd-0e3829a85e99.PNG)
</details>

**Comment by jaballogian** [comment]
I also tried using another smartphone with this specification:

OS version: Android 9
Device manufacturer: Nokia
Device model: Nokia 3 (TA-1032)
I got the same result (HyperTrack SDK was not running) as seen in the screenshots below

<details>
<summary>
Pictures
</summary>

![Screenshot_20210507-144935](https://user-images.githubusercontent.com/24468466/117416848-fb606400-af43-11eb-84a5-3dc4067ce452.png)
![Capture 7](https://user-images.githubusercontent.com/24468466/117417173-42e6f000-af44-11eb-82d8-e68c254ccc0f.PNG)

</details>

I wonder what's wrong then 😂

**Comment by deniszpua** [comment]
@jaballogian I checked the logs and can see `MismatchSenderId` error, which means the firebase key you've set doesn't match the google-services.json, you used to build the quickstart. You can verify, that your device works correctly by downloading our Visits app (you can use the invite from [Dashboard](https://dashboard.hypertrack.com/apps).
As for the HyperTrack Live and Visits apps, I'd recommend, that you change the package name, if you build them from open source, as they are connected to our project by default.
I'd propose that you close this issue and post your messages on our [Slack support channel](https://join.slack.com/t/hypertracksupport/shared_invite/enQtNDA0MDYxMzY1MDMxLTdmNDQ1ZDA1MTQxOTU2NTgwZTNiMzUyZDk0OThlMmJkNmE0ZGI2NGY2ZGRhYjY0Yzc0NTJlZWY2ZmE5ZTA2NjI) for more real time conversation.

**Comment by jaballogian** [comment]
Okay then, I will join the Slack support channel
Thanks for all of your answers 😁
